### ISSUE TITLE
Come up with a better way to do the "diffstate hack"

### ISSUE THREAD

**Issue by jdahlstrom** [vaadin/framework8-issues#105]
In Vaadin 7 field implementations have to resort to a hack to properly update the client if a value change listener decides to reset the value back to what it was before the change: diffstate thinks nothing has changed even though the value already changed on the client.

This is a general problem when the client optimistically updates the value without waiting for confirmation from the server. There should be better API to force an update than calling a low-level ConnectorTracker method.

**Comment by jdahlstrom** [comment]
API suggestion: `void markAsDirty(boolean force)`

**Comment by Artur-** [comment]
Forcing an update is not the real reason for the diff state update, so I can't see how `markAsDirty(boolean)` would help. 

The diffstate is a copy of the client side state on the server,  so if the client side optimistically updates the state, the server needs to update its copy of the client side state  to match. Failing to do so will might leave out updates to the client OR send updates to the client which should not be sent (e.g. textfield must not send the text to the client while the user is typing because in that case the value keeps getting reset to the server version).

The "real" fix would be to transport client side state updates (e.g. `getState().text="foo"`) to the server and apply them to the copy of the client side state

**Comment by Artur-** [comment]
Moved to https://dev.vaadin.com/ticket/20339
