### ISSUE TITLE
HasValue::setReadOnly

### ISSUE THREAD

**Issue by jdahlstrom** [vaadin/framework8-issues#142]
**Design added in a comment after design meeting.**
Do readOnly and required make sense with Listings and/or SelectionModels? Basically with selection "read only" can be understood to mean "no selection allowed" and "required" to mean "no null select allowed". Should we implement those semantics or something else?

**Comment by pleku** [comment]
Adding readonly to HasValue makes sure all fields and listings get it. 
- Remove setReadOnly from Component
- Move AbstractComponent setReadOnly to AbstractLegacyComponent and -Connector
- Add setReadOnly to HasValue
  - read only will prevent all user originated value change events

**Comment by Artur-** [comment]
What does e.g. a read only grid mean? That you can't select but you can still edit the data using the editor?

**Comment by pleku** [comment]
There is no editor currently in Grid. And seems like Grid might not implement HasValue in the end.

Read only for Grid might mean many things, and depending on who you ask you might get a different answer. As long as the editor is not enabled by default, and can be disabled separately, read only should IMO now only effect the _VALUE_ which is the selection.

**Comment by Artur-** [comment]
Once somebody reviews and approves https://dev.vaadin.com/review/#/c/14625/, you can also disable user selection separately

**Comment by Legioth** [comment]
This change would move `setReadOnly(boolean)` to `HasValue` instead of `Component`. Individual implementing components would still be free to also make other aspects unmodifiable (preferably with that mentioned in javadocs as well), but the general contract would be explicitly defined in terms of how `getValue()` can change.

Components that overload `setReadOnly` to affect multiple aspects should also provide fine-grained access to each individual aspect so that an application developer can control what is actually unmodifiable. This responsibility could also be mentioned in the javadoc of `HasValue.setReadOnly`.

**Comment by tsuoanttila** [comment]
Review: https://dev.vaadin.com/review/#/c/14655/
