### ISSUE TITLE
Support empty selection caption in ComboBox

### ISSUE THREAD

**Issue by hesara** [vaadin/framework8-issues#163]
Split off from #65: Like in Vaadin 7, ComboBox should enable the use of a special item that represents null selection and isn't in the data source.

**Comment by Artur-** [comment]
It should not support "null" selection, it should support "empty" selection

**Comment by hesara** [comment]
ComboBox supports empty selection, but doesn't yet let the user specify a non-empty caption for it

**Comment by jdahlstrom** [comment]
Do we need a separate method for it or just specify that ItemCaptionGenerator(null) is invoked to get the empty caption? Or do we need to support a "null object" returned by the selection model if nothing is selected? If needed the user can always do `getSelectedItem().orElse(myNullItem)`

**Comment by Artur-** [comment]
Passing "null" to `ItemCaptionGenerator` would break all basic use cases, e.g. 

```
ComboBox<Person> cb = new ComboBox<>();
cb.setItemCaptionGenerator(Person::getName);
```

**Comment by Artur-** [comment]
Why wouldn't this just be a setter in `ComboBox` and other components supporting empty selection this way? E.g. `setEmptySelectionAllowed(boolean)` and `setEmptySelectionCaption(String caption)`

**Comment by pleku** [comment]
@Legioth please clarify is this a part of the "new DoDo" and add or close.

**Comment by elmot** [comment]
Decided on API for following:
`setEmptySelectionAllowed(boolean)` and `setEmptySelectionCaption(String caption)`(and getters)
We have to take care of:
- Number of items on client side
- Keyboard filtering
- Lost focus behaviour

**Comment by denis-anisimov** [comment]
One step back :
what's the semantic of `setEmptySelectionCaption(String caption)` ?
Does it imply `setEmptySelectionAllowed(true)`?
Otherwise API is confusing: I can set something which never be used if some other method is not called. This is bad design.
Standalone `setEmptySelectionAllowed(boolean)` has sense: empty string will be used for empty selection.
Standalone `setEmptySelectionCaption(String caption)` doesn't make sense.
So it should imply `setEmptySelectionAllowed(true)` and perhaps has different name to express that it implies empty selection.

**Comment by denis-anisimov** [comment]
https://dev.vaadin.com/review/#/c/14842/
