### ISSUE TITLE
Handle the case when client side tries to deselect something which is not selected

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#230]

**Comment by jdahlstrom** [comment]
Is handled and explicitly no-op, but could have debug logging or something.

**Comment by Legioth** [comment]
What are the conditions that lead to this happening?
- Client was slightly out of sync because the selection was recently changed on the server
- Bug in the client implementation
- ???

For an out-of-sync message, the best would probably just be to ignore it.

For a broken implementation, it would be best to scream as loudly as possible in non-production mode so that the issue gets fixed and any potentially harmful secondary effects can also be avoided.

**Comment by pleku** [comment]
COULD HAVE, but not necessary for FW8.
