### ISSUE TITLE
Correct documentation for RadioButtonGroup/CheckBoxGroup instead of OptionGroup

### ISSUE THREAD

**Issue by elmot** [vaadin/framework8-issues#237]
Book of Vaadin contains a lot of references to OptionGroup
Javadoc contains a lot of references to OptionGroup

These needs to be changed to refer to the correct class

**Comment by denis-anisimov** [comment]
BoV contains a section OptionGroup which refers to the old OptionGroup.
There are also several references to it from other places.

Should this be updated actually (replaced)?
Or there should be new sections for new components ?
The question is valid since there is f.e. documentation for compatibility treetable, table components. So old components are still there.

CheckBoxGroup/RadioButtonGroup requires completely new documentation and I'm not sure this is a task for our team.......

**Comment by denis-anisimov** [comment]
https://dev.vaadin.com/review/14522

**Comment by denis-anisimov** [comment]
See #369 for images.
