### ISSUE TITLE
When using a bean with a Grid, I want to be able to automatically configure Grid columns from the bean properties so that I do not have to write a lot of boilerplate code

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#250]
In Vaadin 7 you can do

```
new Grid(new BeanItemContainer<Person>(Person.class));
```

Something similar is needed in 8, e.g.

```
grid = new Grid<Person>();
grid.setColumnsFromBean(Person.class);
```

or to be consistent with BeanBinder:

```
grid = new BeanGrid<Person>(Person.class);
```

**Comment by hesara** [comment]
The first is probably needed - either in Grid or in a helper elsewhere - to make extending Grid easier without having to duplicate all the work in subclasses

**Comment by jdahlstrom** [comment]
Some current Grid API based on property ids that could be based on property names in a hypothetical BeanGrid:
- addColumn
- getColumn
- removeColumn
- setColumns
- setColumnOrder
- sort
- header/footer join

In the "regular" V8 Grid these methods will presumably take Column references instead, although those are somewhat awkward to work with. If a regular Grid has its columns auto-created based on bean properties, it becomes pretty impossible to use the Column reference based APIs.

**Comment by jdahlstrom** [comment]
Some preliminary ideas if automapping properties to columns with a regular Grid is desired:
- The automapper could return a map of the columns it created
- The automapper could assign column ids from property names instead of using KeyMapper
  - And make Column.getId() public API
  - What happens if a column is removed and a new one created, bound to the same property?

**Comment by Artur-** [comment]
```
public class ComplexPerson {
    private String firstName, lastName;
    private Integer age;
    private Date birthDate;
    private BigDecimal salary;
    private boolean alive;
    private Gender gender;
    private ComplexAddress address;

    // + getters setters
}

public enum Gender {
    MALE, FEMALE, UNDISCLOSED;
}

public class ComplexAddress {

    private String streetAddress = "";
    private String postalCode = "";
    private String city = "";
    private Country country = null;
    // + getters setters
}
```

Use cases to support:

1 Configure grid to show all fields in a bean

```
setContent(new Grid<>(ComplexPerson.class));
```
- Configures 8 columns in the same order as the getters are defined in the bean.
- Column headers are in a "human friendly" format, i.e. "First Name", "Last Name","Age","Birth Date", "Salary", "Alive", "Gender", "Address"
- Content are rendered as strings, e.g. "Address@2611421" is ok

2 Configuration from bean, without an "id" column

```
grid = new Grid<>(ComplexPerson.class);
grid.removeColumn("id");
```

3 Configuration from bean, different order with some dropped fields

```
grid = new Grid<>(Person.class);
grid.setColumns("firstName","lastName","age"); // Deletes other columns
```

4 Bean sub properties

```
grid = new Grid<>(Person.class);
grid.expandColumn("address"); // Removes "address", adds "address.streetAddress","address.postalCode", "address.city", "address.country" where the "address" column was
```

5 Low level API used to provide bean columns and usable to create e.g. a custom MapGrid

```
grid = new Grid<T>(new ColumnProvider<T>() {
    public Column addColumn(Grid grid, String id) {
           return grid.addColumn(SharedUtil.capitalize(id), map -> String.valueOf(map.get(id)), new TextRenderer());
    }

    public Stream<String> getDefaultColumns() {
          return Stream.of("first", "last", "age");
    }

   default Stream<String> getExpandedColumns(String id) {
throw new UnsupportedOperationException("The used column provider ("+getClass().getName()+") does not support expansion of columns");
    }
});
```

**Comment by Artur-** [comment]
Depends on #337

**Comment by jdahlstrom** [comment]
Please don't use streams to represent short lists of typically literal values. Or lists or sets in general. It's just semantically so wrong.

**Comment by Legioth** [comment]
"A sequence of elements supporting sequential and parallel aggregate operations."

Sounds like exactly the semantics that we're after here. I would have opted for `ImmutableSequence<T>` if there would have been something like that in the JRE. I'd like to avoid `List<T>` unless random-access or mutability is a desired property.

**Comment by jdahlstrom** [comment]
The semantics wanted here have _absolutely nothing_ to do with sequential and parallel aggregate operations. These return values are not meant for pipelining aggregate operations using fork-join parallelism, with strict single-pass iteration. Mutability is irrelevant, would be nice if there were a real immutable list/set but doesn't matter if not. Run-time unmodifiability is good enough. Use List if order matters, Set if it doesn't and uniqueness matters. Collection (or in some cases, Iterable) for no promises. If random access is provided that's fine, it doesn't hurt if it is there, and typically is reasonable if ordering is provided (if the default columns are "first", "last", "age" in that order, why shouldn't I be able to get the second element in the order?)

You're trying to use a saw to drive nails into wood because the hammer also has this weird hook head that you don't want to use...

**Comment by Legioth** [comment]
The primary use case is not that the user would provide a static list of values, but rather that the values could be the result of some sequential or parallel aggregate operations.

One might instead consider something like iterating through a given metadata description, filter out irrelevant properties, flatmap the remaining to expand sub properties, and finally map everything to property name strings.

In general, I think Stream is a quite nice thing to ask for since you can quite efficiently produce one no matter from which direction you're coming. List/Set/Collection often requires some up-front copying unless you already have the answer in exactly the right format. Iterable or Iterator would often be semantically suitable, but again hard to produce in practice unless you already copy the results into e.g. a List.

**Comment by Artur-** [comment]
http://stackoverflow.com/questions/24676877/should-i-return-a-collection-or-a-stream

"The one case where you must return a Collection is when there are strong consistency requirements, and you have to produce a consistent snapshot of a moving target. Then, you will want put the elements into a collection that will not change.

So I would say that most of the time, Stream is the right answer -- it is more flexible, it doesn't impose usually-unnecessary materialization costs, and can be easily turned into the Collection of your choice if needed. "

Maybe this Brian Goetz dude knows what he is talking about

**Comment by pleku** [comment]
SHOULD HAVE, but not necessary for FW8.

**Comment by mstahv** [comment]
Setting up pretty basic data tables with current Grid in alpha7 requires quite a lot of boilerplate code. Is there any way we could squeeze this into 8.0? Simple things should be simple.

cc: @macjuan

**Comment by amahdy** [comment]
+1

**Comment by mstahv** [comment]
This is what happens without this feature:

https://github.com/mstahv/trackanalyzer/commit/71f238815761fb825e1b80dbd056eaa4a4b7eab9

**Comment by caalador** [comment]
Also see issue #8258 (v7)

**Comment by Legioth** [comment]
> This is what happens without this feature

&lt;realism&gt; The "cost" of getting this fixed in the way I've been imaging it would probably be less than one day. My hunch right now is that a theoretical one day delay of 8.0.0 would be a good trade-off, but I still cannot make any absolute promises. &lt;/realism&gt;

&lt;sarcasm&gt; Oh look. Now it's possible to just read the code and actually know what it does.  &lt;/sarcasm&gt; 

&lt;besserwisser&gt; Why are you doing `.toString()` all over the place instead of just using method references? https://github.com/vaadin/framework/pull/8180 that makes that possible has been in snapshots for 9 days already. &lt;/besserwisser&gt;

**Comment by mstahv** [comment]
If it is just about one day, and I'd have a vote, I'd vote for the delay. Many apps use DTOs and then they'd need no configuration at all to get the relevant stuff on their screen. Even if they'd need to do some configuration for a column or two, it just feels much more efficient if you can easily get something on your screen in 20secs vs. 5 minutes, not to mention how much better that looks in our marketing material ;-)

**Comment by mstahv** [comment]
For the besserwisser, I used beta1, good to hear that toString issue is fixed (again).

**Comment by denis-anisimov** [comment]
I have several comments:
- at the moment it has a label 8.1.0. If it's true then why it's in the candidates list ?
- I'm pretty sure it requires design.

If it requires design then this is not a one day work (as it's shown by our practice).
My first suggestion would be :  provide some generic configurator interface which can be implemented by anyone.
- by default this configurator is not used at all.
- there can be default implementation of this configurator which introspects the bean properties and add columns 
- Grid can accept this configurator as a parameter in the CTOR.
This approach will allow to avoid boilerplate code but each time when you want to avoid it you will understand what you are actually doing: some preexisting configurator which you are aware of. And there is no magic : you know what you do.

**Comment by Legioth** [comment]
I've got a prototype implementation of this already. I'll figure out one edge case and eventually push for review.
