### ISSUE TITLE
Profile memory usage with in-memory data sources

### ISSUE THREAD

**Issue by hesara** [vaadin/framework8-issues#256]
Create a JUnit test that measures the heap usage difference between showing 1 user and 1.000.000 users in the application done in #386

**Comment by denis-anisimov** [comment]
https://dev.vaadin.com/review/14583

Test produces separate results for 1 item in a Grid(V7+V8) and 100000 items in a Grid(V7+V8).
No need to subtract heap usage for 1 item and million.
Million is replaced to 100 000 since 1million is too big and server throws OutOfMemory Error.
Measurement is done directly (without heap size calc).

**Comment by denis-anisimov** [comment]
Previous patch is abandoned.
New one is https://dev.vaadin.com/review/#/c/14584/
