### ISSUE TITLE
Migrate to GitHub workflow

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#263]

**Comment by hesara** [comment]
Some initial thoughts on some of the things needed for this (a very incomplete list):

* go through open changes in gerrit
* go through drafts in gerrit (especially if the original author is not available, one can only abandon a draft by first publishing it - needs to be done before switching the project to read-only mode)
* update contribution instructions (website, readme/relnotes files, ...)
* warn internal and external users EARLY of the implications
* warn about ticket migration related e-mails early, not the day before migration
* both CI servers have many build configurations to update
* check all settings and integrations for the GitHub repository
* add comments on all open changes in Gerrit and switch gerrit to read-only mode
* reopen all relevant PRs in GitHub that have been closed with a comment about using gerrit for contributions
* check all Trac tickets, especially those in "pending-release" state
* update release checklists
* update repository tagging scripts

**Comment by hesara** [comment]
The main topics:
* code migration
* issue migration

While doing this, the repository in GitHub will be renamed to "framework." This will create an automatic redirect in GitHub as long as the old name isn't used for something else.

What needs to happen before code migration:
* start to push to branches on GitHub rather than to gerrit (or hold back changes)
* disable replication from gerrit to GitHub
* make gerrit read-only
* set up all integrations in the vaadin repository
* rename the repository in GitHub

What needs to happen before issue migration:
* coordinate with Anna about whether open BFPs will be closed automatically in trac
* check what to do about feature votes (currently 82 issues)
 * these should not be closed without coordination with Anna and Tatu as the feature vote portlet would lock the votes
 * disable pro account access to dev.vaadin.com (Anna)
* early warning for internal and external users
* test BFP portlet (already in staging - Artur/support team)
* release 7.7.6 to close everything pending for it

Issue migration will be done in batches over about 20h.

What needs to happen after code migration:
* reopen pull requests closed because of gerrit in GitHub
* update contribution instructions (vaadin.com/contribute, CONTRIBUTING.MD, ...)
* update all POMs to point to the correct SCM
* update all references on both CI servers
* update all build scripts
* update release checklists
* update repository tagging scripts

What needs to happen after issue migration:
* BFP system update (Anna, Vappula)
 * no way to automatically migrate open tickets, but there are only a few of them
* test BFP portlet
* making Trac read-only
* updating how 7.7 release notes are built
* update all POMs to point to the correct issue system
* update front page of dev.vaadin.com
* ask marketing to eliminate vaadin.com/bug
* check all tickets in pending release state
* handle open feature votes

**Comment by hesara** [comment]
Status: code migration done except for the following steps:
* reopen pull requests closed because of gerrit in GitHub
* update contribution instructions (vaadin.com/contribute, CONTRIBUTING.MD, ...)
* update all POMs to point to the correct SCM
* remove obsolete build scripts

**Comment by hesara** [comment]
Contribution guide and POM updated, and obsolete build scripts removed. Pages on vaadin.com will be updated after issue migration, which affects them more.

Based on a first quick check, there are 16 PRs that might still be relevant and haven't been addressed yet: 1, 2, 9, 11, 13, 14, 24, 27, 36, 54, 61, 62, 63, 64, 65, 66

**Comment by hesara** [comment]
Using git submodules for screenshots to enable branch agnostic validation builds (see vaadin/framework#86 and vaadin/framework#88) and updated build configurations and repository tagging script generation accordingly.

**Comment by hesara** [comment]
Added comments to recent PRs that had been closed because of Gerrit. We might want to re-pick vaadin/framework#36 that was merged as a PR and then overwritten by Gerrit-GitHub sync.

**Comment by hesara** [comment]
Tickets from the "Core Framework" project have been migrated and Trac is read-only for non-R&D users with registration of new users deactivated and dev.vaadin.com front page updated. Updating of release notes in 7.7 is covered by vaadin/framework8-issues#222 .

**Comment by hesara** [comment]
Feature vote functionality and vaadin.com/bug communicated to the concerned parties. Vaadin 7.7 related issues covered by #222. Migration of miscellaneous minor components from Trac can be done separately. Other tasks done.
