### ISSUE TITLE
Change functional interfaces so they define a method instead of extending Consumer

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#264]

**Comment by Legioth** [comment]
The main reason for this is that generic functional interface names do not make sense, e.g. `apply` for a validator.

Redefining to not use e.g. `Consumer` loses the existing default methods for e.g. chaining (like `Consumer.andThen`), but those offer very little value in our case since the return value then is a `Consumer` instead of the extending type.

**Comment by jdahlstrom** [comment]
I very much disagree. The official guideline is also to use the vocabulary types when there is no good semantic reason not to (eg. not every T->U is a Function, for instance if it has side effects). Specifically, Validator.apply makes _perfect_ sense to me and eg. "Validator.validate" would be just redundant. Besides, they are an implementation detail anyway. If/when relevant, extending types can override provided default methods with proper covariant return types.

**Comment by jdahlstrom** [comment]
If/when relevant, extending types can override provided default methods with proper covariant return types. For instance, Validator.andThen makes perfect sense and is already there (but is called chain - don't really remember why. Perhaps for consistency with Converter.) Especially if we add Validator.orElse, chain should be renamed.

**Comment by Artur-** [comment]
`Validator.validate` communicates exactly what the method does, `Validator.apply` is a bit vague. Still it works reasonably well for validators, but `DataSource.apply`, what are you supposed to do there? 

It is not an implementation detail unless you live in a world where everybody only use lambdas for everything.

**Comment by Legioth** [comment]
It would be easier to see the benefits of retaining e.g. `Consumer` if there would be some real-world-ish code example that highlights the benefits of doing it that way.

Does the "official guideline" apply to using the types as parent types, or is it more about using them directly, which in our case would mean that we wouldn't have a `Validator` type at all, but instead directly use `Function<T, Result<T>>` in the API definition?

**Comment by jdahlstrom** [comment]
The main problem in our case is the need to extend Serializable as well. IMHO it would almost make sense to just have SerializableFunction, SerializableConsumer etc and use those instead of eg.  a bunch of identical-up-to-naming, redundant ItemStyleProvider, ItemCaptionProvider, ItemWhateverProvider etc. Java as a language has been overly obsessed with names up till now IMHO, partially due to the lack of good abstractions.

A Validator still is-a function, it takes an argument and returns a result and does not have side effects (and is not supposed to throw). It makes sense to have it as a separate subtype due to helper default methods and static constructors. I believe it's also good documentation that it extends Function, it immediately tells the user something about it.

DataSource definitely is not a function anymore and should not extend Function as it's not even a functional interface anymore! That one's just something that's accidentally remained. If DS were a functional interface, then it would make sense to be a Function - it's a function from a query to a result set. `DataSource.apply(Query)` doesn't read particularly well but that's partially because the name DataSource is not very function-y.

**Comment by Legioth** [comment]
So is there a code example that highlights why it's beneficial that `Validator` extends `Function`?

**Comment by pleku** [comment]
@Legioth please clarify, is this part of the "new DoDo" ? Close if not.

**Comment by mstahv** [comment]
I'd do this, this would make some things so much easier to figure out when using our APIs.

**Comment by hesara** [comment]
The changes that will make it to beta1 have been made. There might be additional changes for filtering later, but they will be handled separately.
