### ISSUE TITLE
Make primary stylenames of select components consistent while retaining BW compatibility

### ISSUE THREAD

**Issue by jdahlstrom** [vaadin/framework8-issues#317]
The default primary stylenames of select components are weird due to _extremely_ legacy reasons:
- NativeSelect and ListSelect are `v-select`
- TwinColSelect is `v-select-twincol`
- OptionGroup is `v-select-optiongroup`
- ComboBox is `v-filterselect`.

These are inconsistent with basically every other component and a cause of minor WTFs when writing custom styles. 

I propose changing the default primary stylenames as follows, but also keeping the old stylenames for now, documenting that they are deprecated.
- NativeSelect to `v-nativeselect`
- ListSelect to `v-listselect`
- TwinColSelect to `v-twincolselect`
- RadioButtonGroup to `v-radiobuttongroup`
- CheckBoxGroup to `v-checkboxgroup`
- ComboBox to `v-combobox`.

This change will still break selectors relying on the `v-primarystylename-customstylename` prefixed versions of custom stylenames, but those shouldn't really be used anyway and if necessary, the primary stylename can always be set by the user on a per-component instance basis while migrating.

**Comment by Legioth** [comment]
Suggestion for how this should work:

Styles of a new NativeSelect: `v-nativeselect v-select`
Styles after `addStylename("foo")`: `v-nativeselect v-select v-select-foo foo`
Styles after `setPrimaryStyleName("bar")`: `bar bar-foo foo`

We would still need to keep using the old selectors in the built-in themes since it would otherwise cause problems with the legacy components, that would basically need a separate legacy version of valo to work.

**Comment by Legioth** [comment]
I also talked with Rolf. His general feeling was that we'd upset more people than we'd delight by removing the old stylenames.

**Comment by pleku** [comment]
Since the way this should be done and how we still need to support the old style names, this has been descoped from 8.0.0. Would be nice to have, but not a MUST.
