### ISSUE TITLE
Fix vaadin-root dependency management leaking to customer projects

### ISSUE THREAD

**Issue by tsuoanttila** [vaadin/framework8-issues#383]
Either:
1. Go back to using properties to define dependency version numbers
2. Make vaadin-bom not use parent pom (this means fixing every single build configuration to correctly update vaadin-bom version number)
3. Something else if you have a better idea.

Test with a project using Vaadin BOM and make sure it uses dependency version from your project, not from Vaadin BOM.

**Comment by pleku** [comment]
Any ideas, @Artur- ?

**Comment by pleku** [comment]
After fixing the "leaking", https://github.com/vaadin/vaadin/commit/cc479e9a44200f13001074d58903e6f2baa5253d
should be reapplied.

**Comment by Artur-** [comment]
Are there other problems which could arise from vaadin-bom (which is in practice used in all projects where Vaadin is used) depending on the framework root pom (which is afaik considered to "just be a part of the framework project itself")?

**Comment by pleku** [comment]
Any other issues ? Don't know of any other than the one that caused opening this ticket, which is that dependency versions from "leaking" from vaadin framework POM in to the framework BOM might override versions that BOM users have specified.

This can be worked around pretty easily(?) :
_Dependency mediation - this determines what version of a dependency will be used when multiple versions of an artifact are encountered. Currently, Maven 2.0 only supports using the "nearest definition" which means that it will use the version of the closest dependency to your project in the tree of dependencies...
"nearest definition" means that the version used will be the closest one to your project in the tree of dependencies, eg. if dependencies for A, B, and C are defined as A -> B -> C -> D 2.0 and A -> E -> D 1.0, then D 1.0 will be used when building A because the path from A to D through E is shorter. You could explicitly add a dependency to D 2.0 in A to force the use of D 2.0_

Which means that any leaking dependency version can be easily overridden by specifying the correct version in the actual POM.

But, then again, not sure if these "common" dependencies for the framework can be specified somewhere else than in the root POM, e.g. another "dependency" module on which the framework submodules then depend ? That way the Vaadin framework specified versions should not be that high up in the "nearest definition" chain that they won't _that_ easily override user specified ones.

Or then just switch back to using version properties defined in the root POM and used in the submodules.

**Comment by Artur-** [comment]
Can't see when we ever would want to have something leak from the project root pom to the BOM file. I would just make the BOM project standalone

Based on a quick glance, https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html seems to advocate that the bom project should be the topmost project and what is currently our "root" project should extend that, and not the other way around.

**Comment by pleku** [comment]
https://dev.vaadin.com/review/#/c/14595/
