### ISSUE TITLE
Shorthand for single selection in SelectionEvent

### ISSUE THREAD

**Issue by pleku** [vaadin/framework8-issues#397]
SelectionEvent should have `getFirstSelected() : Optional<T>`

**Comment by denis-anisimov** [comment]
There is com.vaadin.event.SelectionEvent which has no any relation to any V8 component.
(which means that it probably should be moved into compatibility module).

And there are separate SingleSelectionChange and MultiSelectionEvent classes that extend ValueChange.
I believe this issue is about those two classes.
And the questions are:
- is it only about MultiSelectionEvent  ?
- should there be a common interface for  SingleSelectionChange and MultiSelectionEven which has requested method ?

**Comment by pleku** [comment]
Very good points. SelectionEvent should be moved, yes.

Otherwise I'm not sure if there needs anything else do be done. We can discuss further during daily, maybe I misunderstood what @tsuoanttila meant originally during the design meeting.

**Comment by denis-anisimov** [comment]
https://dev.vaadin.com/review/14614
