### ISSUE TITLE
Consider renaming setItems method

### ISSUE THREAD

**Issue by mstahv** [vaadin/framework8-issues#412]
Item is a bad word for us to use here.

 - We have already spoiled it in previous versions of the framework. There will be sh|tload of misconceptions because of old documentation and discussions in the internet.
 - It ("item") doesn't clearly tell what you are setting. Good code should be like a story. E.g. setRows (for components with tabular data) and setOptions (for select components) would be much better for both new and existing developers. Those have proven to work very well in Viritin.

Otherwise that part of the API really rocks, so long items and containerdatasources! Good work guys!

**Comment by Legioth** [comment]
One challenge with the suggested `setRows` and `setOptions` names is that different components would have differently named methods that essentially do the same thing.

**Comment by Artur-** [comment]
What exactly is the challenge? Discoverability?

Does not sound like a huge issue that the API for setting values for select components targeted for forms (`setOptions`) is different than the API for setting data to show in a grid / data table (`setRows`). This is also consistent with HTML naming.

**Comment by Legioth** [comment]
`<vaadin-grid>` and `<vaadin-combo-box>` both use `items` as the name of the property that defines the data that is shown. We should be consistent with Core Elements, so either suggest changes there as well, or then be happy with `setItems` in the Java API as well.

**Comment by mstahv** [comment]
I have not used those Core Elements, but `<row>` and `<option>` would be much better tag names there as well.

**Comment by pleku** [comment]
Might consider adding duplicate versions of `setItems` with a more suitable method name `setRows / setOptions` for that component, that just forwards to `setItems`.

**Comment by Legioth** [comment]
Do we have any DX results that indicate which option is more logical to users?

**Comment by mstahv** [comment]
This starts to strike me more and more when preparing Vaadin 8 related marketing material, tutorial etc. Is someone working on this? Should this issue (and others still in this repo) be moved to the actual framework repository?

**Comment by Legioth** [comment]
Nobody is working on this since there hasn't been any real-world DX results that would imply that this is actually an issue. Introducing new methods that does the same thing but with different names might actually just add to the confusion if the user doesn't know whether to use `setItems` or e.g. `setRows`.

**Comment by mstahv** [comment]
AFAIK you have no DX tests at all, so these changes are made based on feeling anyways. I hope you don't excpect community members to do "DX tests" for each and every feature. I could in theory make a poll to a largish portion of our users, but that is not possible for most contributors.

I don't really buy your argument of people getting confused of methods. If somebody finds the setRows method, he sure should be happy with that. In documentation we should refer to more domain specific methods as they can have better javadocs with links to related methods. See the pull request I just created a moment ago. It could contain even more references to methods that users can use to format the options/rows, but I just can't find more time to invest on this now.

In general it looks to me the whole HasItems is an obsolete abstraction. There may be something I haven't seen, but if it would be my decision with this knowledge, we would get rid of the generic methods altogether.

**Comment by Legioth** [comment]
So far, I've seen one data point in favour of changing this and one data point against. With those two data points being your opinion and my opinion, it's not very much to go on.

Vaadin Ltd is a gatekeeper for what goes into our products. If some community member wants to introduce a change that we do not agree with, then the community member needs to do much more convincing than if it's a change that we also think would be a good fit for the product.

One thing feels quite certain for me: there should only be one set of methods. If we open the box of including duplicates for any names that someone might feel is more natural, then we'd also have to consider anyone who feels that e.g. `setData`,  `setValues` or `setAlternatives` would be a better fit.

I'm still open for discussing whether `setItems` or `setRows` would make more sense, but I'm very strongly against introducing any duplicates.

**Comment by jouni** [comment]
> I have not used those Core Elements, but `<row>` and `<option>` would be much better tag names there as well.

Just to make it clear, there isn’t an element named `<items>` in any of our elements. There’s an attribute/property named `items`, i.e. `<vaadin-grid items="...">` and `<vaadin-combo-box items="...">`.

That name was mainly used because that is what the Polymer team has chosen to use in their elements, and we wanted to be consistent within the Polymer ecosystem.

**Comment by robeden** [comment]
I agree with @mstahv's first argument. "Item" meant something very specific in Vaadin 7.x. I don't know that it's insurmountable, but it would be confusing when learning 8.x.

**Comment by mstahv** [comment]
@Legioth there has been three people (Artur, Johannes, Fredu) in addition to me reacting positively for my suggestion in this issue. You are the only one I know who favour setItems and I have discussed about the topic with several developers.

More natural, self-documenting names and less confusion among current users (also with users who'll need to use older Vaadin versions for many years on) are such a strong arguments that I could tolerate even some "duplication" here. I left them intact in my pull request as I thought it might help to get the better named variants in. We can then later favor them in documentation and tutorials. But as said, because I'm not involved in the daily development of the framework anymore, I don't know if there is a reason to have this *HasItems* interfaces and its methods at all. If we can easily, I agree with you, that we should get rid of it. 

IMO, the "gatekeeper" should be so proud of the framework that it would treat this kind of "community proposals" with respect and realise there is often a confirmation bias when suggestion "competes" against your own inventions. If there is no unanimous solution, it is the "gatekeeper" that should do the "DX tests". A single community member most probably don't have the resources to do such.

**Comment by jouni** [comment]
I’m also slightly leaning on Leif’s side, that we shouldn’t introduce aliases, and that we should be consistent with the upcoming web component implementations. But I probably have the least amount of experience in actually building stuff with the framework, so my 2c are worth less than yours.

One question to @Legioth: does it make any difference, that vaadin-grid 2.0 will have the `items` property to set the data as an array, and the `dataSource` property for providing the data through a callback function (lazy loading)? Will we have two methods in the server-side grid for those also?

---

If we ignore the fact that we have legacy APIs using the word “item”, would you still consider the method name confusing? I think that’s an important question also, as we are redesigning this API to be with us for the next 5–10 years (?), and in that time all legacy code or API will have much less relevance to this discussion as today.

Isn’t the API still doing the exact same thing as previously, if you think about it logically? You had “items” in FW7, and now you’re still “setting items for a grid”.

Won’t the compiler will tell you if you still try to stuff legacy `Item` objects in there? From there on, is it still unclear what you need to do to fix your code? If it’s unclear, are there other ways to make it clear than by introducing alias methods?

---

Anyway, this is really quite pointless to debate this for so long without user testing. Would be great if we could try this out some real users, but I’m not exactly sure who would take the ball on that?

**Comment by mstahv** [comment]
I made a UX test for you and based on it some people have some issues with their head (chose setData :-) )
https://twitter.com/MattiTahvonen/status/822174963847299072

**Comment by Legioth** [comment]
> does it make any difference, that vaadin-grid 2.0 will have the `items` property to set the data as an array, and the `dataSource` property for providing the data through a callback function

That's almost perfectly in sync with how it's done in FW8 as well, with the exception that we had to change "data source" to "data provider" to avoid conflicts with `javax.sql.DataSource`.

> I made a UX test for you

The test is quite partial since it leads towards one of the alternatives by including the word "options" in the question. What if the question would instead have been "... natural to set *items* to your ..." or "... natural to set *data* to your ..."??

**Comment by jouni** [comment]
Well, I wouldn’t call that a UX test, but good info nonetheless. The question already aligns expectations to go towards “setOptions”. And I would agree, that for a “select” component, options is clearly the best option. But for a data grid – I’m not looking to set options there, that’s clear – what am I giving it? Items, data, rows? All of those seem pretty equal. “Rows” probably wins because that’s what you usually get from a database, and how you refer to them in the visual outcome.

I guess the Polymer team has opted for the more abstract “items” so that it can be used for all of their similarly functioning elements (`dom-repeat` and `iron-list` being the most important ones). But, they also use `<paper-item>` as the child element for select-like components like [`<paper-dropdown-menu>`](https://www.webcomponents.org/element/PolymerElements/paper-dropdown-menu). But paper-item is a more general purpose element again, so it wouldn’t make sense to call it ”paper-option”.

**Comment by mstahv** [comment]
Dudes, I should start using my emoji keyboard all to time with you. Of course it depends on how you set the question and I knew that when did the poll. But it still tells something. I'm confident that option is the best word for selects, especially in our case.

The web component I and most other web developers know is called select and it has option elements in it. http://www.w3schools.com/tags/tag_option.asp

IIRC at least Java FX also uses item, it is not the worst possible options, but they don't have the history with "Item" we do.

For Grid rows is a natural choice.

**Comment by robeden** [comment]
> If we ignore the fact that we have legacy APIs using the word “item”, would you still consider the method name confusing? I think that’s an important question also, as we are redesigning this API to be with us for the next 5–10 years (?), and in that time all legacy code or API will have much less relevance to this discussion as today.

IMO, no, I wouldn't consider it confusing without the historical background. I would personally prefer "items" to "options" without that baggage. With that consideration, it's probably just best to call it out in a migration guide.

JavaFX [does use "items"](http://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/ChoiceBox.html#setItems-javafx.collections.ObservableList-).

I'd also consider "data" acceptable, though perhaps a bit generic.

I don't really like "options" as that makes me think of customizing the operation of the control.

**Comment by elmot** [comment]
There is already `setData` in all components, not related to rows or content even a little.
IIRC we discussed `setOptions`, and performed some DX testing, and found that very confusing. 
> I don't really like "options" as that makes me think of customizing the operation of the control.

+1, that was most confusing for us as well.

Also I'll vote against `setRows`, because in case of horizontal `RadioButtonGroup`/`CheckBoxGroup` those are columns.

**Comment by pleku** [comment]
As @elmot explained, there was DX testing done on this last summer, and based on the feedback it was decided not to change the naming for 8. 

The discussion today with the FW team keeps getting to the conclusion:
- no aliases in FW API
- _items_ is the best alternative for all cases (OptionGroups, Grid, Selects, Tree...)
  - we like that it doesn't change between components, you know that one method works for all instead of trying figuring out "oh right grid uses rows"
  - In my personal opinion, e.g. when demoing the API, it has a nice effect when you can change the component and the API is the same, you don't have to change the method name just because you switched from ComboBox to Grid
- using _options_ for Selects and _rows_ or e.g. Grid would lead into unsynced API related to e.g. selection, `getSelectedItem` works for all but after changes it would be `getSelectedRows` or `getSelectedOption` for some ...
- _data_ is a concept that is used already, and changing that would lead into yet another migration step and confusion to introduce for 8
- _dataItems_ was thought of too weird because then we'd have _data_ and _dataItems_ and just not adding any value on top of _items_ 
- _bean_ would not make sense since it is not really a Java Bean you're setting
- _content_ is taken already by SingleComponentContainer or such, and it works badly for e.g selects

For us it seems that there is no better option than _items_. Also note that the work amount for changing the API is not just about renaming one method, but others that have similar API and all the documentation, examples ...

So, we need further convincing to accept this.

**Comment by mstahv** [comment]
@elmot I think nobody has suggested to add setRows method to selects of any kind, setRows for Grid, setOptions for selects as I did in the related PR: https://github.com/vaadin/framework/pull/8270. IMO those are the names we should use, with the arguments above (Item word is wasted already, option and row are natural words for the domain, aligns with element names (well, "tr" in table is not exactly row, but that's a bad naming in html ;-) )).

I don't buy the argument of easy swapping between selects and tabular data presentation components, nobody really does that, I don't remember even me doing that in any demos. There is most often some component specific configuration anyway, which requires much greater changes. In selection API, the method name could be simply *getSelection*.

Also, note that you still need to override the javadocs for Grid and select components. setItems there and what related methods should be referred there are so different from. See the PR what I suggested there. That part can probably be even better, but the docs should at least refer to addColumnn methods in Grid and caption/icon provider in selects.

What ever you do, the great thing is that current setItems is much better for developers than current API that forces for Container magic. That probably still makes me cry many times in the future.

BTW. Unrelated thingie, isn't setData deprecated yet? That is such a bad feature that we should get rid of it. (Just to make sure, if it wouldn't exist, I still wouldn't like that name for neither Grid or selects.)

**Comment by pleku** [comment]
At this point we have no plans of getting rid of `setData` just to confuse existing migrating users that use that obscure feature.

As for now, we have considered renaming and decided against it. In the future it is though highly likely, that the server side component API will 1:1 with the corresponding web component in regards to naming, so then it will depend on each component for what the API will be.
