### ISSUE TITLE
Client-to-Server RPC calls for disabled components

### ISSUE THREAD

**Issue by pleku** [vaadin/framework8-issues#415]
There are certain cases, where a disabled component must do a call from client to server to e.g. request for data to display (even though it is disabled). 

Related to #286 

- this annotation is method level, not inherited
- checked on invocation for disabled component
- client side doesn't have any general check for disabled rpc calls, depends on connector
- need to use this in a test component

**Comment by Artur-** [comment]
Please keep in mind that disallowing RPC for disabled components is a fundamental security feature in the framework, just like disallowing RPC for detached components.

**Comment by Legioth** [comment]
Introduce an `@AllowWhenDisabled` annotation that marks that a specific RPC method handler on the server can be invoked even if the connector is disabled.

The javadocs of the annotation should clearly warn about the security implications of this feature.

The annotation must be on a server-side RPC handler implementation method declared in the class of the instance that is passed to `registerRpc` and not just not on the RPC interface. Since the regular convention is that these kinds of annotations are on the RPC interface and not on the implementation, we should also look for the annotation on RPC interface methods and raise an error that informs the developer that the annotation is not supported there.

When receiving RPC invocations from the client for a disabled connector, the warning that is produced by `ServerRpcHandler.getIgnoredDisabledError` should be logged only if no registered RPC handler for the current method is annotated.

**Comment by Artur-** [comment]
Why is this needed at all?

**Comment by Legioth** [comment]
The primary case is that Grid should be able to show a full set of data even if it's rendered as initially disabled. The server cannot know how many rows will be needed, which from the regular users's point of view will give the impression that Grid is broken if the initially pushed set of rows is not enough.

Features such as scrolling and resizing might further impact this.

**Comment by pleku** [comment]
After discussion, decided to postpone this since it is not strictly needed for any 8.0 issue or use case.

**Comment by denis-anisimov** [comment]
The main reason of this issue is fixed here : https://dev.vaadin.com/review/#/c/14454/.
As a part of this ticket #286.

Proper fix should remove the workaround from https://dev.vaadin.com/review/#/c/14454/

**Comment by pleku** [comment]
This is a not needed, won't fix and invalid after https://github.com/vaadin/vaadin/commit/24b43d902c71ea469e2105f3a1c8be2f84610f04

**Comment by denis-anisimov** [comment]
I'm not so sure.
We are enabling only one dedicated connector. Looks like a hack.

**Comment by pleku** [comment]
I don't see it as a hack, I see it as a framework implementation detail. There have so far been good reasons why rpc calls are ignored for disabled components, and shoud avoid opening that door to prevent any misuse from happening.

If we get another case or someone requests for this feature, then it can be taken into consideration.

**Comment by denis-anisimov** [comment]
Implementation details should be hidden for the end user.
DataCommunication extension is a regular extension. 
If we consider this as an impl detail ( which is totally fine) then make it totally invisible for an app developer. Right now it's visible for an app developer and it has confusing behavior : why one extension which looks like regular extension has special handling whereas others don't ?

It introduces some mess because logic is not localized. This is always bad and always has impact in the future.

From my opinion this is definitely a hack. But this is just my opinion.

**Comment by pleku** [comment]
Fair points. This hack has been done for Vaadin Window too, which can be closed even when it is disabled, it is just using V6 style communication. If that would be migrated to V7 style communication, we would have another candidate for using this feature and probably should then implement it, instead of using the hack.
