### ISSUE TITLE
setItems method should be overloaded with Stream

### ISSUE THREAD

**Issue by mstahv** [vaadin/framework8-issues#447]
Many new Java libraries are built on Stream usage. Even if Vaadin component couldn't use Stream natively, we should provide an API to accept Stream directly. The currrent state accepts just array and Collection.

**Comment by Legioth** [comment]
I have a some concerns with accepting Stream in this way. It kind of implies that something like `IntStream.range(0, 100000).mapToObj(TestPerson::new)` could be processed without consuming huge amounts of memory, which is obviously not the case. For this reason I would prefer that the collection into a List or Array would be explicitly written out in the application code instead.

On the other hand I also see that it could be a convenient shorthand in many cases.

**Comment by mstahv** [comment]
Yes, I think it would be good idea to express the fact that the whole stream shall be marshalled to JavaDocs. But getting rid of extra boilerplate code easily overcomes the "concern" of some people not knowing how the Grid in Vaadin works.

Hopefully in the future at some point we'll have a luxury of having Grid that don't require knowing the size connected data -> could work more efficiently with some streams and databases.

**Comment by Legioth** [comment]
You're assuming developers read javadocs before they are stuck with something? In this case I'd even assume that if they get stuck with excessive memory consumption, the wouldn't even know which javadoc to read since the problem might from their point of view come from any part of the code.

In general, I'd like to challenge the notion that less code is always better. Code is written once, but read and modified many times. It might therefore be beneficial that any potential surprises are explicitly spelled out instead of being hidden behind a helper API. Most developers are proficient with touch typing and using the auto complete features of their IDE, so those additional ~20 characters is not a very big obstacle.

**Comment by mstahv** [comment]
Well, if you want to put this to this level, to me it looks like you are underestimating your users and making precautions for memory consumption is more important than a good API.

I definitely agree that less code is not always better, but here you are making people repeat themselves (or making all developers extend Grid with a similar helper). Seriously, I still haven't seen any good arguments why we should force many vaadin developers in the future, maybe even several times per day, to write

    g.setItems(stream.collect(Collectors.toList()));

instead of

    g.setItems(stream);

#FFS, lets  make it simple.
