### ISSUE TITLE
Validate that Vaadin Framework 8 archetypes work correctly in Netbeans

### ISSUE THREAD

**Issue by pleku** [vaadin/framework8-issues#453]
* application
* application-example
* multimodule
* widget
NOTE: does not include liferay archetype

**Comment by denis-anisimov** [comment]
Application archetype is tested. Works fine.

**Comment by denis-anisimov** [comment]
vaadin-archetype-java-ee-application is tested. Works fine.

**Comment by denis-anisimov** [comment]
widget archetype is tested. Works fine.

**Comment by denis-anisimov** [comment]
application-example is tested. Works fine.

Only multimodule archetype remains. It is waiting for update to V8.

**Comment by hesara** [comment]
Both #348 and #476 will update the application-example archetype, so quick retesting after those changes may be needed.

**Comment by denis-anisimov** [comment]
Example is tested. Works fine.
 #348  is already integrated.
#476 is not yet.

**Comment by denis-anisimov** [comment]
I don't like the idea of keeping this ticket open just because of #476.
#476 is in the backlog and blocked in the sprint which belongs different track.
Which means we will be waiting for this for indefinite time while our sprint ends tomorrow.

Please create a ticket to test example archetype only once #476 is fixed.
It might be that there will be a number of tickets which will change some archetypes. We cannot keep the ticket open forever (indefinite time).
