### ISSUE TITLE
Type erasure causes problems in BeanBinder

### ISSUE THREAD

**Issue by ahie** [vaadin/framework8-issues#466]
For example if I have a bean with a member field `Set<Category> category` and a field component that `implements HasValue<Set<Category>>` I should be able to automatically bind it with BeanBinder's bindInstanceFields, instead I get an exception with the following message: 

"Property type 'java.util.Set' doesn't match the field type 'java.util.Set<org.test.samples.backend.data.Category>'. Binding should be configured manually using converter."

**Comment by denis-anisimov** [comment]
The reason is : 
there is a declaration `SomeClass implements HasValue<Set<Category>>` but `Category` is erased in runtime from this generic declaration and it becomes smth like `SomeClass implements HasValue<Set>`. So there is a raw `Set` instead of generic. And we can't do anything with that.
There are two ways:
- let it be as is, so user should do manual binding in this case.
- erase a type from generic and make it raw. That may be not good since it's not type safe. But we can agree that we do it in such cases. So we just compare raw types , ignoring parameters (it has some sense). Otherwise we are losing automatic bindings for any listings.

**Comment by pleku** [comment]
Decided to erase the generic type and make it raw.
