### ISSUE TITLE
TwinColSelect selection works differently than in Vaadin 7

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#468]
If you compare `com.vaadin.tests.components.twincolselect.TwinColSelectTestUI` and `com.vaadin.tests.components.select.TwinColSelectTest` you can see a couple of differences in how the V7 and V8 TwinColSelects work (set nullselection allowed + multiselect for the V7).

1. Select the first item, click `add`, click `add` again
* 7.7: Adds the first item and then the second item
* 8.0.alpha7: Adds the first item

2. Have one item selected, click "remove"
* 7.7: Focuses the first selected item so that another "remove" will remove it
* 8.0: Focuses the right (value) select element but no option

3. Select an item in the right (value)  select and click "remove"
* 7.7: The item is removed and the right (value) select is focused
* 8.0.alpha7: The item is removed, selected in the left (options) select and the right (value) select is focused

Should these have changed?

**Comment by Artur-** [comment]
@jouni, any input on how it should be?

**Comment by jouni** [comment]
I don’t see any particular reason why this should have changed, if the existing behavior hasn’t been criticized by our users.

On the other hand, a major version upgrade does give us the freedom/right to make these kinds of changes, so we can re-evaluate the behavior if we want to. But, since I believe we want the transition from FW7 → FW8 to be as smooth as possible, any unnecessary breakage can be considered a bad thing.

So, I suggest we restore the previous behavior if possible with reasonable effort, and re-evaluate the behavior in FW9 when the client side implementation is going to change completely.
