### ISSUE TITLE
Excessive requests when opening ComboBox dropdown

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework8-issues#488]
When opening the dropdown of a ComboBox, three separate XHR requests are sent. This is not noticeable with when the network is fast since the dropdown still opens in about 100ms, but it's very annoying over a slower network connection.

A maximum of one round trip should be needed.

**Comment by Artur-** [comment]
There should be no XHRs if you just open the popup

**Comment by hesara** [comment]
It seems the fix for #286 reduced the requests for opening the popup to two: one that sets the filter and as a side effect resets the data communicator, and another that then requests new data. When just opening the popup and all the items are in memory, it should not be necessary to make two requests - one might be needed to refresh the data from the server, but its response should then include pushed rows.
