### ISSUE TITLE
AddColumn with empty caption to grid breaks the whole Vaadin application.

### ISSUE THREAD

**Issue by rogozinds** [vaadin/framework8-issues#494]
If you do something like this
```
                    Grid<ItemThing> grid = new Grid<>();
                    grid.setDataSource(new ListDataSource<>(items));
                    grid.setHeight("200px");
                    grid.setWidth("200px");
                    grid.addColumn("", ItemThing::getValue);
```
The whole application is handling with
com.example.MyAppWidgetset-0.js:7814 Wed Nov 23 10:36:48 GMT+200 2016 com.vaadin.client.ApplicationConfiguration
SEVERE: The json to handle cannot be null
java.lang.IllegalArgumentException: The json to handle cannot be null
	at Unknown.Hi(com.example.MyAppWidgetset-0.js)
	at Unknown.Ji(com.example.MyAppWidgetset-0.js)
	at Unknown.f3e(com.example.MyAppWidgetset-0.js)
	at Unknown.dmc(com.example.MyAppWidgetset-0.js)
	at Unknown._8b(com.example.MyAppWidgetset-0.js)

**The error handling should be done in a better way.**
Add javadoc, that column caption can not be an empty string.

**UPD:** If you aad a space as an identifier you get ArrayIndexOutOfBoundsException.

**Comment by Legioth** [comment]
The bug should be fixed instead of documenting this as a limitation, unless there's some specific technical reason for why  `""` or `" "` cannot work.

**Comment by tsuoanttila** [comment]
The string in there is not the caption but the identifier for the Column. Will add some sanity checks to the addColumn method to not allow bad identifiers.

**Comment by Legioth** [comment]
Remind me again why a column needs a human-assigned identifier.

**Comment by tsuoanttila** [comment]
https://github.com/vaadin/framework8-issues/issues/337 some discussion back in the day related to this issue. Someone (I don't remember who) made lots of noise to be able to give an identifier for a column.

**Comment by tsuoanttila** [comment]
If we deem that users don't need to be able to define their own identifiers, I'm completely fine making a quick patch removing said feature to being only autogenerated IDs.

**Comment by nikkijuk** [comment]
If there's no more identifiers for column how users are able to combine header cells? of course one could do this over objects addColumn (..) returns, but it means giving up some flexibility and already used conventions.

Example:

    HeaderCell cell = header.join(
       header.getCell(FIELD_1),
       header.getCell(FIELD_2));
    cell.setText("name");

**Comment by Legioth** [comment]
@nikkijuk In what way is it less flexible to use the `Column` instance that you get from `addColumn`?

**Comment by nikkijuk** [comment]
@Legioth Field name constants (static) can be set up easily before building grid and used as long as needed. Column objects need to be saved in some stateful storage structure after creation if you need to access metadata of Grid. I really don't know if there's important difference on this - especially if there's no other use case for column objects than manipulating grid headers / footers .. My 2 cents: As you currently afford to change API you can implement support for both variants (internally using column objects) and if all works with column objects well and looks solid then drop named variant as duplicate during beta period.

**Comment by Legioth** [comment]
What we want to avoid is that the API for column identifiers can be confused to mean something else, as is apparent from the originally reported issue.

What prevents us from changing the functionality from having a less prominent location in the API is that the identifiers are currently also used for internal bookeeping, which means that we cannot allow them to change after the column has originally been changed.

We should change the internal implementation to always use internally generated identifiers for the internal bookeeping, and then only use application-provided identifiers for targeting a specific column in other APIs. With that done, the API could be changed so that `Column` has a `setIdentifier` method that can be chained with other operations for configuring the column. The result would thus be that instead of `grid.addColumn("foo", callback).setCaption("Something")`, you'd write `grid.addColumn(callback).setIdentifier("foo").setCaption("Something")`.

We should then also preserve the old functionality that the identifier also serves as the default caption for the column by making the column use the human readable representation of the identifier unless a caption has been explicitly set.
