### ISSUE TITLE
Consider sorting with a similar approach as filtering

### ISSUE THREAD

**Issue by tsuoanttila** [vaadin/framework8-issues#499]
As of right now, our only component that supports Sorting is Grid. Grid works with sorting due to a custom hack and hardcoded types for backends and in-memory data. It might be beneficial to the users to allow conversions and default sorting.

**Comment by Legioth** [comment]
The drawback with that approach is that it would introduce a thrid type parameter for `DataProvider`. I also don't see exactly how this would work in practice: what would the "native" sort definition type produced by `Grid` be, i.e. what is is that should in some cases be converted to a list of property name + sort order tuples and sometimes to a `Comparator<T>`?

I would instead propose that the API in `Grid` is left as it is, but the `Query` API is changed so that both kinds of information are always made available to the `DataProvider`,  regardless of its type. The implementation is then free to use the data that it needs. This would be feasible in the case of sorting since two types of data are enough to cover basically all the known use cases, compared to filtering where there's a larger variation in how the input could be defined.
