### ISSUE TITLE
ViewChangeListener should be split in two

### ISSUE THREAD

**Issue by mstahv** [vaadin/framework8-issues#502]
Normally people don't need after view change at all, it should be split to separate listeners. This also would make it functional interface -> make it possible to use lambdas/method references.

//cc @johannesh2

**Comment by Legioth** [comment]
An alternative to splitting could be to introduce an overload of `addViewChangeListener` that accepts something corresponding to a `Consumer<ViewChangeEvent>` that only reacts to `beforeViewChange`.

**Comment by denis-anisimov** [comment]
I personally would prefer to go with different approach than both suggested.
Both suggestion are about introducing new methods into Navigator.
So instead of having two methods in the interface which requires implementation by the developer we introduce two or even more methods that are implemented by ourselves BUT they are not obvious , they require javadoc (which nobody reads) and some thinking which method to use.
Also there will be weird names for the methods in the Navigator class (long ones, with "before" and "after" in the middle) which just complicates the understanding what they are about.

The current approach is good in a sense that there is only one method in the Navigator class which the developer should use. And then logically all the functionality is in the one place. It's much easier to understand what does listener do.

The original issue is valid as well. In reality many developers just don't need the second method at all.
This can be solved via Adapter class or nowadays we can just provide an empty implementation for the `afterViewChange` in the `ViewChangeListener` interface.

The benefits are:
- minimal number of changes
- quite known "adapter" pattern
- logically it's better to have one interface per functionality
- those who really wants the functionality will be able to find the method and override it without any issue.

In my opinion it's the best approach here.
I'm not going to do right know anything with this ticket. Will wait for a feedback.

**Comment by Legioth** [comment]
Good idea! Simply providing an empty default implementation for `afterViewChange` (and marking the interface as `@FunctionalInterface`) would probably be the simplest way of dealing with this.
