### ISSUE TITLE
ColorPicker and ColorPickerArea required indicator is not shown

### ISSUE THREAD

**Issue by anssit** [vaadin/framework8-issues#504]
Setting requiredIndicatorVisible to true has no visible effect on ColorPicker or ColorPickerArea in any of the layouts.

**Comment by denis-anisimov** [comment]
See #459 for the reference.
Both components manages their captions by themselves.
But they don't contain a logic for required indicator.

Nowadays they are fields but client side logic has not been updated (previously they had not "required" property).

**Comment by denis-anisimov** [comment]
Actually this is the same situation as with CheckBox:
why do I want to have `required` indicator for ColorPicker ?
Because I use it as a user verification component and want a color selection from the user to be sure that it's done explicitly and the selected color is not white (default).
Quite artificial usecase. But why not ?
So those components should support required indicator.
