### ISSUE TITLE
Consider changing Binder.saveIfValid to return Result instead of boolean

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#95]

**Comment by Legioth** [comment]
Please show code

**Comment by Artur-** [comment]
Not sure why this issue exists, let's not do it

**Comment by jdahlstrom** [comment]
This is contingent on #140. If `validate` returns a `Result`, as it IMO should, and originally did, it makes no sense not to return that result from `saveIfValid` too.

**Comment by Legioth** [comment]
What is the use case for when it would be useful for saveIfValid to return a `Result` (or actually a `Collection<Result>`)?

`saveIfValid` is intended as a shorthand that you'd use together with an `if` statement. Changing it to return `null` instead of `false` would make it less convenient for that one case that it's been designed for. If you want to do something more complicated, then you should probably use `validate` instead.

**Comment by jdahlstrom** [comment]
Obviously it would not return null, ever. Or a Collection<Result> (but Result needs some extra stuff to make bundling several results easier). 

The common idiom would be `if(saveIfValid(bean).isOk())` which IMO reads well enough and  you'd still get the result if needed. Or in many cases `saveIfValid(bean).ifOk(...)` reads even better. With just `validate` you get the problem that you can't then call `save` without catching the checked exception... and the `if(validate().isOk()) { saveIfValid(); }` pattern doesn't read too well at all.

**Comment by Artur-** [comment]
`saveIfValid(foo).isOk()` sounds strange, then it should just be `save(foo).ifOk`

**Comment by jdahlstrom** [comment]
I actually meant to add that `saveIfValid` could be renamed to `trySave()`

**Comment by Legioth** [comment]
The problem with `trySave()` is that it wouldn't appear as an autocomplete suggestion for `save`.

I'm still failing to understand the use case where it would be useful to get anything else than a boolean when calling that method. What does the user want to achieve?

**Comment by Artur-** [comment]
If this is still relevant, please add a use case and reopen
